# Generated by Django 3.2.12 on 2022-03-07 08:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books',
            options={'verbose_name_plural': '图书列表'},
        ),
        migrations.AlterField(
            model_name='books',
            name='borrower',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books_borrower', to=settings.AUTH_USER_MODEL, verbose_name='借出人'),
        ),
    ]
