# Generated by Django 3.2.12 on 2022-03-15 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='mobile',
            field=models.IntegerField(null=True, verbose_name='手机号码'),
        ),
    ]
