# Generated by Django 3.2.12 on 2022-03-07 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20220307_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='borrow_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='借出时间'),
        ),
    ]
