# Generated by Django 3.2.12 on 2022-03-16 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_userprofile_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.SmallIntegerField(choices=[(1, '预定中'), (2, '已借阅'), (3, '归还中'), (4, '已归还'), (5, '已取消')], verbose_name='状态'),
        ),
    ]
