# Generated by Django 3.2.12 on 2022-03-08 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_alter_books_borrow_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='入库时间'),
        ),
        migrations.AlterField(
            model_name='books',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '正常'), (1, '借出中'), (2, '已借出'), (3, '归还中')], default=0, verbose_name='书籍状态'),
        ),
    ]
