# Generated by Django 3.2.12 on 2022-03-08 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_rename_books_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '正常'), (1, '预定中'), (2, '已借阅'), (3, '归还中')], default=0, verbose_name='书籍状态'),
        ),
    ]
