# Generated by Django 3.2.12 on 2022-03-09 03:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_alter_book_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name_plural': '书籍'},
        ),
        migrations.RemoveField(
            model_name='book',
            name='borrow_time',
        ),
        migrations.RemoveField(
            model_name='book',
            name='borrower',
        ),
        migrations.RemoveField(
            model_name='book',
            name='status',
        ),
        migrations.AddField(
            model_name='book',
            name='count',
            field=models.IntegerField(default=1, verbose_name='库存'),
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(blank=True, null=True, verbose_name='操作时间')),
                ('status', models.SmallIntegerField(choices=[(1, '预定中'), (2, '已借阅'), (3, '归还中'), (4, '已归还')], verbose_name='状态')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_book', to='book.book')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_username', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name_plural': '日志表',
            },
        ),
    ]
