# Generated by Django 3.2.12 on 2022-03-09 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_rename_time_history_m_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='content',
            field=models.TextField(null=True, verbose_name='内容简介'),
        ),
        migrations.AddField(
            model_name='book',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='book_img/%Y/%m/%d/', verbose_name='书籍图片'),
        ),
    ]
