# Generated by Django 3.2.12 on 2022-03-09 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_auto_20220309_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='内容简介'),
        ),
    ]
