# Generated by Django 3.2.12 on 2022-03-09 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_alter_book_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name_plural': '图书列表'},
        ),
        migrations.AlterField(
            model_name='book',
            name='img',
            field=models.ImageField(blank=True, default='book_img/default.img', null=True, upload_to='book_img/%Y/%m/%d/', verbose_name='书籍图片'),
        ),
    ]
