# Generated by Django 3.2.12 on 2022-03-09 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0011_auto_20220309_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='img',
            field=models.ImageField(blank=True, default='book_img/default.ipg', null=True, upload_to='book_img/%Y/%m/%d/', verbose_name='书籍图片'),
        ),
    ]
