# Generated by Django 3.2.12 on 2022-03-09 07:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0012_alter_book_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('status', models.SmallIntegerField(choices=[(1, '预定中'), (2, '已借阅'), (3, '归还中'), (4, '已归还')], verbose_name='状态')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_book', to='book.book')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_username', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name_plural': '操作记录',
            },
        ),
        migrations.DeleteModel(
            name='History',
        ),
    ]
