# Generated by Django 3.2.12 on 2022-03-13 09:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0013_auto_20220309_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('status', models.SmallIntegerField(choices=[(1, '预定中'), (2, '已借阅'), (3, '归还中'), (4, '已归还')], verbose_name='状态')),
            ],
            options={
                'verbose_name_plural': '借阅订单',
            },
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': '用户列表'},
        ),
        migrations.AlterField(
            model_name='book',
            name='img',
            field=models.ImageField(blank=True, default='book_img/default.jpg', null=True, upload_to='book_img/%Y/%m/%d/', verbose_name='书籍图片'),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.IntegerField(null=True, verbose_name='手机号码'),
        ),
        migrations.DeleteModel(
            name='Record',
        ),
        migrations.AddField(
            model_name='order',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_book', to='book.book', verbose_name='书名'),
        ),
        migrations.AddField(
            model_name='order',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_username', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
